apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: products.k8sinitiative.3scale.net
spec:
  group: k8sinitiative.3scale.net
  names:
    kind: Product
    listKind: ProductList
    plural: products
    shortNames:
    - pdcs
    singular: product
  scope: Namespaced
  version: v1alpha1
