apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  namespace: k8sinitiative
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      serviceAccountName: products-admin
      namespace: k8sinitiative
      containers:
        - name: web-server
          image: quay.io/didierofrivia/go-fetch-products:latest
          env:
            - name: NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: k8s-initiative-configmap
                  key: namespace
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  -name: k8s-initiative-configmap
                  key: web_server_port
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
              readOnly: true
          volumes:
            - name: config-volume
              configMap:
                name: k8s-initiative-configmap
