kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: products-read-rb
subjects:
- kind: ServiceAccount
  name: products-viewer
  namespace: k8sinitiative
roleRef:
  kind: Role
  name: products-read
  apiGroup: ""
